package paxoslocker.grader;

import org.junit.jupiter.api.Assertions;
import paxoslocker.diagnostics.WorkerEventType;
import paxoslocker.model.*;
import paxoslocker.protocol.DecisionMessage;
import paxoslocker.testkit.*;
import paxoslocker.transport.MessageEnvelope;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.Consumer;

final class IntegrationScenarioSupport {
    static final Duration WAIT=Duration.ofSeconds(8);
    static NoOp command(){return new NoOp(UUID.randomUUID());}
    static void run(ClusterConfig config,Consumer<ClusterHarness> scenario){try(ClusterHarness c=ClusterHarness.start(config)){try{scenario.accept(c);}catch(Throwable failure){throw new AssertionError(failure.getMessage()+"\n"+c.diagnostics(),failure);}}}
    static void stableCommand(ClusterHarness c){c.awaitLeader(WAIT);Command command=command();c.submit(command);Command decided=c.awaitDecision(1,WAIT);c.awaitExecutedThrough(1,WAIT);c.awaitReplicaConvergence(WAIT);Assertions.assertEquals(command.requestId(),decided.requestId());}
    static void sequential(int count){run(ClusterConfig.small(),c->{c.awaitLeader(WAIT);for(int i=0;i<count;i++)c.submit(command());c.awaitDecision(count,WAIT);c.awaitExecutedThrough(count,WAIT);c.awaitReplicaConvergence(WAIT);});}
    static void concurrent(int clients){run(ClusterConfig.small(),c->{c.awaitLeader(WAIT);try(var executor=Executors.newVirtualThreadPerTaskExecutor()){List<Future<?>> futures=new ArrayList<>();for(int i=0;i<clients;i++)futures.add(executor.submit(()->c.submit(command())));futures.forEach(f->{try{f.get();}catch(Exception e){throw new RuntimeException(e);}});}c.awaitDecision(clients,WAIT);c.awaitExecutedThrough(clients,WAIT);c.awaitReplicaConvergence(WAIT);});}
    static void lockerConflict(){run(ClusterConfig.small(),c->{c.awaitLeader(WAIT);c.submit(new ReserveLocker(UUID.randomUUID(),"one","locker-1"));c.submit(new ReserveLocker(UUID.randomUUID(),"two","locker-1"));c.awaitDecision(2,WAIT);c.awaitExecutedThrough(2,WAIT);c.awaitReplicaConvergence(WAIT);c.replicaIds().forEach(r->Assertions.assertEquals(LockerStatus.RESERVED,c.inspectReplica(r).applicationState().get("locker-1").status()));});}
    static void competingProposals(){run(ClusterConfig.small(),c->{c.awaitLeader(WAIT);List<NodeId> r=c.replicaIds().stream().toList();Command a=command(),b=command();try(var ex=Executors.newVirtualThreadPerTaskExecutor()){ex.submit(()->c.submitTo(r.get(0),a));ex.submit(()->c.submitTo(r.get(1),b));}c.awaitDecision(2,WAIT);c.awaitExecutedThrough(2,WAIT);c.awaitReplicaConvergence(WAIT);Set<UUID> ids=new HashSet<>();c.inspectReplica(r.getFirst()).decisions().values().forEach(x->ids.add(x.requestId()));Assertions.assertTrue(ids.containsAll(Set.of(a.requestId(),b.requestId())));});}
    static void outOfOrderDecision(){run(ClusterConfig.small(),c->{NodeId replica=c.replicaIds().iterator().next(),leader=c.leaderIds().iterator().next();Command one=command(),two=command();c.sendForTest(MessageEnvelope.of(leader,replica,new DecisionMessage(2,two)));Assertions.assertEquals(0,c.inspectReplica(replica).lastExecutedSlot());c.sendForTest(MessageEnvelope.of(leader,replica,new DecisionMessage(1,one)));Await.until(()->c.inspectReplica(replica).lastExecutedSlot()>=2,WAIT,"ordered execution after hole fill");});}
    static void leaderScenario(String kind){ClusterConfig cfg=kind.equals("three")?new ClusterConfig(1,3,3,3,WAIT,123456):ClusterConfig.small();run(cfg,c->{if(kind.equals("beforeScout")){NodeId victim=c.leaderIds().iterator().next();c.crashLeader(victim);c.awaitLeader(WAIT);c.restartLeader(victim);stableCommand(c);return;}NodeId old=c.awaitLeader(WAIT);Command x=command();if(kind.equals("duringCommander")){c.submit(x);Await.until(()->!c.inspectLeader(old).runningCommanders().isEmpty(),WAIT,"Commander before leader crash");}else if(kind.equals("afterChosen")||kind.equals("oldReturns")){c.submit(x);c.awaitDecision(1,WAIT);}c.crashLeader(old);NodeId next=c.awaitLeader(WAIT);Assertions.assertNotEquals(old,next);c.restartLeader(old);if(!kind.equals("duringCommander")&&!kind.equals("afterChosen")&&!kind.equals("oldReturns"))c.submit(x);c.awaitDecision(1,WAIT);c.awaitExecutedThrough(1,WAIT);c.awaitReplicaConvergence(WAIT);});}
    static void leadersCompete(int count){run(new ClusterConfig(1,3,3,count,WAIT,123456),c->{c.leaderIds().forEach(id->c.restartLeader(id));stableCommand(c);});}
    static void acceptorsDown(int f,int n,int down,boolean expectProgress){ClusterConfig cfg=new ClusterConfig(f,n,3,3,WAIT,123456);run(cfg,c->{c.awaitLeader(WAIT);c.acceptorIds().stream().limit(down).forEach(c::crashAcceptor);Command x=command();c.submit(x);if(expectProgress){c.awaitDecision(1,WAIT);}else{Assertions.assertThrows(AssertionError.class,()->c.awaitDecision(1,Duration.ofMillis(500)));NodeId restore=c.acceptorIds().stream().filter(id->!c.isRunning(id)).findFirst().orElseThrow();c.restartAcceptor(restore);c.awaitDecision(1,WAIT);}c.awaitExecutedThrough(1,WAIT);});}
    static void acceptorPersistence(boolean repeated){run(ClusterConfig.small(),c->{c.awaitLeader(WAIT);c.submit(command());c.awaitDecision(1,WAIT);NodeId a=c.acceptorIds().iterator().next();int cycles=repeated?10:1;for(int i=0;i<cycles;i++){var before=c.inspectAcceptor(a);c.crashAcceptor(a);c.restartAcceptor(a);var after=c.inspectAcceptor(a);Assertions.assertTrue(after.ballot().compareTo(before.ballot())>=0);Assertions.assertTrue(after.accepted().containsAll(before.accepted()));}});}
    static void replicaRecovery(boolean gap,boolean multiple){run(ClusterConfig.small(),c->{c.awaitLeader(WAIT);List<NodeId> targets=c.replicaIds().stream().limit(multiple?2:1).toList();targets.forEach(c::crashReplica);for(int i=0;i<5;i++)c.submit(command());c.awaitDecision(5,WAIT);targets.forEach(c::restartReplica);c.awaitExecutedThrough(5,WAIT);c.awaitReplicaConvergence(WAIT);if(gap)targets.forEach(r->Assertions.assertEquals(5,c.inspectReplica(r).lastExecutedSlot()));});}
    static void workerCrash(boolean scout,WorkerEventType event){run(ClusterConfig.small(),c->{if(scout){NodeId leader=c.leaderIds().iterator().next();c.inspectLeader(leader);Await.until(()->c.inspectLeader(leader).runningScoutBallot().isPresent(),WAIT,"Scout");var ballot=c.inspectLeader(leader).runningScoutBallot().orElseThrow();c.workerEvents().killOnNext(leader,ballot,null,event,()->c.failures().killScout(leader,ballot));c.awaitWorkerEvent(leader,ballot,null,event,WAIT);}else{NodeId leader=c.awaitLeader(WAIT);c.submit(command());Await.until(()->!c.inspectLeader(leader).runningCommanders().isEmpty(),WAIT,"Commander");var key=c.inspectLeader(leader).runningCommanders().iterator().next();c.workerEvents().killOnNext(leader,key.ballot(),key.slot(),event,()->c.failures().killCommander(leader,key.ballot(),key.slot()));c.awaitWorkerEvent(leader,key.ballot(),key.slot(),event,WAIT);}c.submit(command());c.awaitDecision(1,WAIT);c.awaitExecutedThrough(1,WAIT);c.awaitReplicaConvergence(WAIT);});}
    static void network(String kind){run(ClusterConfig.small(),c->{NodeId leader=c.awaitLeader(WAIT);List<NodeId> acceptors=c.acceptorIds().stream().toList(),replicas=c.replicaIds().stream().toList();switch(kind){case"delay"->c.failures().delayNext(MessagePredicate.any(),Duration.ofMillis(50));case"duplicate"->c.failures().duplicateNext(MessagePredicate.any());case"drop"->c.failures().dropNext(MessagePredicate.any());case"reorder"->c.failures().reorderNext(MessagePredicate.any());case"leaderPartition"->c.partition(Set.of(leader),Set.copyOf(acceptors));case"replicaPartition"->c.partition(Set.of(replicas.getFirst()),Set.copyOf(c.membership().leaders()));case"minorityPartition"->c.partition(Set.of(acceptors.getFirst()),Set.copyOf(c.membership().leaders()));case"heal"->{c.partition(leader,acceptors.getFirst());c.heal(leader,acceptors.getFirst());}case"staleLeader"->{c.failures().delayNext(MessagePredicate.any(),Duration.ofMillis(100));c.crashLeader(leader);c.awaitLeader(WAIT);}case"staleCommander"->c.failures().delayNext(MessagePredicate.messageType(paxoslocker.protocol.P2aMessage.class),Duration.ofMillis(100));default->throw new IllegalArgumentException(kind);}c.submit(command());c.healAll();c.awaitDecision(1,WAIT);c.awaitExecutedThrough(1,WAIT);c.awaitReplicaConvergence(WAIT);});}
    static void combined(String kind){run(ClusterConfig.small(),c->{NodeId leader=c.awaitLeader(WAIT),acceptor=c.acceptorIds().iterator().next(),replica=c.replicaIds().iterator().next();switch(kind){case"leaderAcceptor"->{c.crashAcceptor(acceptor);c.crashLeader(leader);}case"commanderReplica"->{c.submit(command());Await.until(()->!c.inspectLeader(leader).runningCommanders().isEmpty(),WAIT,"Commander");var key=c.inspectLeader(leader).runningCommanders().iterator().next();c.partition(replica,leader);c.failures().killCommander(leader,key.ballot(),key.slot());}case"scoutStale"->{var ballot=c.inspectLeader(leader).runningScoutBallot().orElseThrow();c.failures().delayNext(MessagePredicate.any(),Duration.ofMillis(100));c.failures().killScout(leader,ballot);}case"oldCommander"->{c.submit(command());Await.until(()->!c.inspectLeader(leader).runningCommanders().isEmpty(),WAIT,"Commander");c.crashLeader(leader);}case"acceptorDuplicate"->{c.crashAcceptor(acceptor);c.restartAcceptor(acceptor);c.failures().duplicateNext(MessagePredicate.any());}case"replicaTraffic"->{c.crashReplica(replica);c.submit(command());c.restartReplica(replica);}case"twoLeaders"->{c.crashAcceptor(acceptor);c.leaderIds().forEach(c::restartLeader);}case"partitionFailover"->{c.partition(Set.of(leader),c.acceptorIds());c.awaitLeader(WAIT);c.healAll();}default->throw new IllegalArgumentException(kind);}c.healAll();if(!c.isRunning(acceptor))c.restartAcceptor(acceptor);if(!c.isRunning(leader))c.restartLeader(leader);if(!c.isRunning(replica))c.restartReplica(replica);c.submit(command());c.awaitDecision(1,WAIT);c.awaitExecutedThrough(1,WAIT);c.awaitReplicaConvergence(WAIT);});}
    static void localTcp(){run(ClusterConfig.localTcpSmall(),IntegrationScenarioSupport::stableCommand);}
    private IntegrationScenarioSupport(){}
}
