package paxoslocker.diagnostics;

public enum ProtocolDiagnosticType {
    NODE_STARTED, NODE_STOPPED, ACCEPTOR_BALLOT, PVALUE_ACCEPTED, COMMANDER_CREATED,
    VALUE_CHOSEN, DECISION_LEARNED, COMMAND_EXECUTED, LEADER_PREEMPTED, MESSAGE_IGNORED
}
