package paxoslocker.diagnostics;

public enum WorkerEventType {SCOUT_CREATED, P1A_BEFORE_SEND, P1A_AFTER_SEND, P1B_RECEIVED, SCOUT_QUORUM_REACHED, ADOPTED_BEFORE_SEND, SCOUT_EXITED, COMMANDER_CREATED, P2A_BEFORE_SEND, P2A_AFTER_SEND, P2B_RECEIVED, COMMANDER_QUORUM_REACHED, DECISION_BEFORE_SEND, DECISION_AFTER_SEND, COMMANDER_EXITED}
