package paxoslocker.testkit;
public enum EventType { MESSAGE_SENT, MESSAGE_DELIVERED, MESSAGE_DROPPED, MESSAGE_DELAYED,
    MESSAGE_DUPLICATED, PARTITIONED, PARTITION_HEALED, NODE_CRASHED, NODE_RESTARTED,
    NODE_PAUSED, NODE_RESUMED, NODE_STARTED, NODE_STOPPED, WORKER_EVENT, WORKER_KILLED,
    COMMANDER_CREATED, VALUE_CHOSEN, DECISION_LEARNED, COMMAND_EXECUTED,
    ACCEPTOR_BALLOT, PVALUE_ACCEPTED, LEADER_PREEMPTED, MESSAGE_IGNORED }
